const productos = [
    {
        valor: 129,
        precio: "129.000 $COP",
        imagen: "Img-Tiendas/imagen2.jpg",
        nombre: "adidas",
        tipo: "camisa",
    },
    {
        valor: 149,
        precio: "149.000 $COP",
        imagen: "Img-Tiendas/imagen3.jpg",
        nombre: "nike",
        tipo: "camisa",
    },
    {
        valor: 139,
        precio: "139.000 $COP",
        imagen: "Img-Tiendas/imagen4.jpg",
        nombre: "lacoste",
        tipo: "camisa",
    },
    {
        valor: 99,
        precio: "99.000 $COP",
        imagen: "Img-Tiendas/imagen5.jpg",
        nombre: "louis",
        tipo: "camisa",
    },
    {
        valor: 139,
        precio: "139.000 $COP",
        imagen: "Img-Tiendas/imagen6.jpg",
        nombre: "adidas",
        tipo: "pantalon",
    },
    {
        valor: 159,
        precio: "159.000 $COP",
        imagen: "Img-Tiendas/imagen7.jpg",
        nombre: "nike",
        tipo: "pantalon",
    },
    {
        valor: 119,
        precio: "119.000 $COP",
        imagen: "Img-Tiendas/imagen8.jpg",
        nombre: "lacoste",
        tipo: "pantalon",
    },
    {
        valor: 129,
        precio: "129.000 $COP",
        imagen: "Img-Tiendas/imagen9.jpg",
        nombre: "louis",
        tipo: "pantalon",
    },
    {
        valor: 89,
        precio: "89.000 $COP",
        imagen: "Img-Tiendas/imagen10.jpg",
        nombre: "adidas",
        tipo: "zapato",
    },
    {
        valor: 79,
        precio: "79.000 $COP",
        imagen: "Img-Tiendas/imagen11.jpg",
        nombre: "nike",
        tipo: "zapato",
    },
    {
        valor: 119,
        precio: "119.000 $COP",
        imagen: "Img-Tiendas/imagen12.jpg",
        nombre: "lacoste",
        tipo: "zapato",
    },
    {
        valor: 99,
        precio: "99.000 $COP",
        imagen: "Img-Tiendas/imagen13.jpg",
        nombre: "louis",
        tipo: "zapato",
    },
]